version: '2.1'

volumes:
  db-data:

services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
    networks:
      - prestashop-network

  prestashop-git:
    hostname: ${PS_HOSTNAME}
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-16.20.1}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}
    environment:
      DB_SERVER: ${DB_SERVER:-mysql}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
    ports:
      - "8001:80"
      - "8002:443"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - prestashop-network

  maildev:
    image: 'maildev/maildev'
    ports:
      - "1080:1080"
    networks:
      - prestashop-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - prestashop-network

networks:
  prestashop-network:
    name: prestashop-network
